### PR TITLE
Dispatch event when request is processed.

### PR DESCRIPTION
**Pull request by jongotlin**
It's handy to dispatch events when the request is made in order to listen to it's result. I particularly need it in https://github.com/jongotlin/BillogramBundle/pull/1 where I show the result in the Symfony Toolbar and add the result to the general logger.

### CODE REVIEW

**Comment by AndreasHogstrom** [comment]
At this time, we would not like to add a dependency for `symfony/event-dispatcher`, as we want this package to be as lightweight and stand-alone as possible.

Maybe a more dynamic and implementation agnostic solution could be thought of?

**Comment by jongotlin** [comment]
Sure. Put it as a suggestion instead.

**Comment by jongotlin** [comment]
Why did you close it? Now the event dispatcher are moved to suggest from require.

**Comment by jongotlin** [comment]
Care to answer why you closed it without explaining why?

**Pull request closed without merging**
